version: '3'

networks:
  op-erigon:
  traefik_proxy:
    external: true
    name: traefik_proxy

volumes:
  op-erigon-data:

services:
  erigon:
    image: testinprod/op-erigon:${TAG:-latest}
    env_file:
      - .env
    entrypoint: /home/erigon/entryscript/erigon.sh
    networks:
      - traefik_proxy
      - op-erigon
    ports: 
      - "${RPC_PORT:-8545}:8545"
    expose:
      - 8551
    volumes:
      - ./entryscript:/home/erigon/entryscript
      - op-erigon-data:/home/erigon/.local/share/erigon
      - ./jwtsecret:/home/erigon/jwtsecret
    restart: unless-stopped
    mem_swappiness: 0
    labels:
      - "traefik_template=name:docker-optimism-archive port:8545 prefix:/"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
    env_file:
      - .env
    entrypoint: /home/erigon/entryscript/op-node.sh
    networks:
      - op-erigon
    volumes:
      - ./entryscript:/home/erigon/entryscript
      - ./jwtsecret:/home/erigon/jwtsecret
    restart: unless-stopped
