version: '3'

networks:
  op-erigon:

services:
  erigon:
    image: testinprod/op-erigon:${TAG:-2.48.1-0.1.8-amd64}
    env_file:
      - .env
    entrypoint: /home/erigon/entryscript/erigon.sh
    networks:
      - op-erigon
    ports: 
      - "8546:8545"
    expose:
      - 8551
    volumes:
      - ./entryscript:/home/erigon/entryscript
      - ./datadir:/home/erigon/.local/share/erigon
      - ./jwtsecret:/home/erigon/jwtsecret
    restart: unless-stopped
    mem_swappiness: 0
    labels:
      - "traefik_template=name:docker-optimism-archive port:8545 prefix:/"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
    env_file:
      - .env
    entrypoint: /home/erigon/entryscript/op-node.sh
    networks:
      - op-erigon
    volumes:
      - ./entryscript:/home/erigon/entryscript
      - ./jwtsecret:/home/erigon/jwtsecret
    restart: unless-stopped
